language: "ruby"

rvm:
  - "1.8"
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "jruby"
  - "rbx"

sudo: false

install:
  - bundle install --retry=3

matrix:
  include:
    - rvm: "2.3"
      gemfile: "gemfiles/Gemfile.multi_json.x"
    - rvm: "2.3"
      gemfile: "gemfiles/Gemfile.yajl-ruby.x"
    - rvm: "2.3"
      gemfile: "gemfiles/Gemfile.uuidtools.x"
  allow_failures:
    - rvm: "1.8"
