language: "ruby"

rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "jruby-1.7"
  - "jruby-9.1"

sudo: false

install:
  - bundle install --retry=3

matrix:
  include:
    - rvm: "1.9"
      gemfile: "gemfiles/Gemfile.ruby_19.x"
    - rvm: "jruby-1.7"
      gemfile: "gemfiles/Gemfile.ruby_19.x"
    - rvm: "2.5"
      gemfile: "gemfiles/Gemfile.multi_json.x"
    - rvm: "2.5"
      gemfile: "gemfiles/Gemfile.yajl-ruby.x"
    - rvm: "2.5"
      gemfile: "gemfiles/Gemfile.uuidtools.x"
