language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - "2.1.2"
  - "jruby"
  - "rbx"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
